paths:
  log_name: exp/learned/smallvgg_cifar10/forget_0-400_10classes
  tensorboard: exp/learned/smallvgg_cifar10/forget_0-400_10classes/tensorboard
  checkpoint: exp/learned/smallvgg_cifar10/forget_0-400_10classes/checkpoints
params:
  epochs: 200
  num_workers: 8
  batch_size: 256
  log_interval: 50
dataset:
  train:
    name: datasets.UnlearnCIFAR10
    root: /home/data/
    params:
      data_set: train
      download: true
      forget_range:
      - - 0
        - 400
      - - 0
        - 400
      - - 0
        - 400
      - - 0
        - 400
      - - 0
        - 400
      - - 0
        - 400
      - - 0
        - 400
      - - 0
        - 400
      - - 0
        - 400
      - - 0
        - 400
      data_section: retain
  test:
    name: datasets.UnlearnCIFAR10
    root: /home/data/
    params:
      data_set: test
      download: true
      data_section: full
net:
  backbone: backbone.SmallVGG
  params:
    num_classes: 10
    dropout: 0.5
SGD:
  method: optim.SGD
  params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
optimizer:
  method: optim.SGD
  params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
scheduler:
  method: CustomExponentialLR
  params:
    start_lr: 0.01
    end_lr: 0.0005
    num_steps: 200
