model: smallvgg
dataset: cifar10
unlearn_steps:
- forget_range:
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
retained_var: 0.95
start_lr: 0.05
end_lr: 0.01
loss_w: 1.0
loss2_w: 0.2
wd: 0
offset: 0.05
num_epochs: 100
num_bins: 101
work_dir: exp/unlearned/smallvgg_cifar10/exp1
