model: smallvgg
dataset: cifar10
unlearn_steps:
- forget_range:
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
- forget_range:
  - - 100
    - 200
  - - 100
    - 200
  - - 100
    - 200
  - - 100
    - 200
  - - 100
    - 200
  - - 100
    - 200
  - - 100
    - 200
  - - 100
    - 200
  - - 100
    - 200
  - - 100
    - 200
  ignore_range:
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
  - - 0
    - 100
- forget_range:
  - - 200
    - 300
  - - 200
    - 300
  - - 200
    - 300
  - - 200
    - 300
  - - 200
    - 300
  - - 200
    - 300
  - - 200
    - 300
  - - 200
    - 300
  - - 200
    - 300
  - - 200
    - 300
  ignore_range:
  - - 0
    - 200
  - - 0
    - 200
  - - 0
    - 200
  - - 0
    - 200
  - - 0
    - 200
  - - 0
    - 200
  - - 0
    - 200
  - - 0
    - 200
  - - 0
    - 200
  - - 0
    - 200
- ignore_range:
  - - 0
    - 300
  - - 0
    - 300
  - - 0
    - 300
  - - 0
    - 300
  - - 0
    - 300
  - - 0
    - 300
  - - 0
    - 300
  - - 0
    - 300
  - - 0
    - 300
  - - 0
    - 300
  forget_range:
  - - 300
    - 400
  - - 300
    - 400
  - - 300
    - 400
  - - 300
    - 400
  - - 300
    - 400
  - - 300
    - 400
  - - 300
    - 400
  - - 300
    - 400
  - - 300
    - 400
  - - 300
    - 400
retained_var: 0.95
start_lr: 0.05
end_lr: 0.01
loss_w: 1.0
loss2_w: 0.2
wd: 0
offset: 0.05
num_epochs: 100
num_bins: 101
work_dir: exp/unlearned/smallvgg_cifar10/exp1
