paths:
  log_name: exp/learned/allcnn_cifar10/forget_0-500_1classes
  tensorboard: exp/learned/allcnn_cifar10/forget_0-500_1classes/tensorboard
  checkpoint: exp/learned/allcnn_cifar10/forget_0-500_1classes/checkpoints
params:
  epochs: 100
  num_workers: 8
  batch_size: 256
  log_interval: 50
dataset:
  train:
    name: datasets.UnlearnCIFAR10
    root: /home/data/
    params:
      data_set: train
      download: true
      forget_range:
      - - 0
        - 500
      data_section: retain
      random_seed: 0
  test:
    name: datasets.UnlearnCIFAR10
    root: /home/data/
    params:
      data_set: test
      download: true
      data_section: full
  val:
    name: datasets.UnlearnCIFAR10
    root: /home/data/
    params:
      data_set: val
      download: true
      data_section: full
net:
  backbone: backbone.AllCNN
  params:
    num_classes: 10
    dropout: false
SGD:
  method: optim.SGD
  params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
optimizer:
  method: optim.SGD
  params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
scheduler:
  method: CustomExponentialLR
  params:
    start_lr: 0.01
    end_lr: 0.0005
    num_steps: 100
